### ISSUE TITLE
TypeError: Invalid file: WindowsPath

### ISSUE THREAD

**Issue by kahotv** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#1]
我在最后推导时出现这个错误，根据网上搜索，解决办法如下：

在inference_main.py的第35行，
wav_path = Path(raw_audio_path).with_suffix('.wav')
改为：
wav_path = str(Path(raw_audio_path).with_suffix('.wav'))

**Comment by SUC-DriverOld** [comment]
感谢指出！
