### ISSUE TITLE
我的显卡是4090，我在训练的时候感觉CPU是100%运行的，但是显卡没有在运行，我怀疑是不是这个在用cpu自带的显存在训练啊

### ISSUE THREAD

**Issue by yanfaze** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#13]
![image](https://github.com/SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents/assets/12097100/44e0b719-f2c7-4048-bc9a-2d6eb1982098)

**Comment by SUC-DriverOld** [comment]
不会，如果是cpu训练会直接报cpu training is not allowed，正常训练确实是会吃一点cpu性能。你目前的状况缺少具体日志，查不出原因。

**Comment by SUC-DriverOld** [comment]
你上面这个截图的报错是内存不够，需要调大虚拟内存，再次重试
