### ISSUE TITLE
訓練模型時GPU占用低，顯存幾乎全滿

### ISSUE THREAD

**Issue by stephen7943** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#14]
**1. 我的設備配置與環境(PC1)**
- Intel i9 12900
- NVIDIA GeForce RTX 2080 super 8GB
- 128.0 GB RAM
- cuda 12.1
- Windows 10 企業版 22H2
- Python 3.8.18
- Pytorch 2.1.2
- 
**2. PC2環境配置**
- Intel i5 13600K
- NVIDIA GeForce RTX 3080 10GB
- 96.0 GB RAM
- cuda 12.1
- Windows 10 家用版 23H2
- Python 3.8.18
- Pytorch 2.1.2

**3. 訓練集為5~20秒，總長165分鐘的音檔**

**4. 遇到的狀況**
在訓練模型時CPU 與GPU占用皆很低，每個epoch 耗時700～800秒( 經過將訓練文件的fp16_run  改為true
後下降到100秒左右)，但我在另一台電腦使用RTX3080 10GB GPU的佔用幾乎是滿的。

**我的日誌**
![螢幕擷取畫面 2024-02-06 115931](https://github.com/SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents/assets/94160194/dd7d507d-63ce-4740-9760-fd8cc98fb4cf)

**CPU占用**
![螢幕擷取畫面 2024-02-06 120204](https://github.com/SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents/assets/94160194/f4f2e2c8-5d83-4355-a922-811b4df3ba10)

**GPU占用**
![螢幕擷取畫面 2024-02-06 120223](https://github.com/SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents/assets/94160194/99fc1f29-2a69-4cb0-85a6-6900c39a4667)

**Comment by SUC-DriverOld** [comment]
从您提供的图片和信息来看，700s出一个epoch是不正常的现象，正常情况一般在100s以内。一般产生这个现象的原因是使用了共享显存。你的一台电脑GPU占用很大，但是另一台占用少有一种可能是吃共享显存导致的。您可以按照下面方法关闭共享显存占用。此外，由于您的总显存大约是72g，而真正有用的显存只有8g，所以即使8g专用显存吃满，占用率也会很低。

训练时CPU占用低属于正常现象，GPU的话训练模型只有专用GPU显存有作用，在您的图片里专用GPU内存只有8G并且是在正常使用的，共享GPU内存请不要使用，使用后会导致训练速度明显的变慢很多倍。

> 在模型训练时，如果使用了共享显存将使训练速度显著降低，需要根据本文档关闭此功能
> NVIDIA SUPPORT：
> 在驱动程序536.40中，我们实现了一种新方法，允许应用程序在耗尽GPU内存的情况下使用共享内存。这使得以前在GPU内存不足时崩溃的应用程序能够继续运行，尽管速度较低。当运行接近GPU内存最大化以实现无缝转换时，会切换到使用共享内存。
模型训练通常需要接近6 GB的GPU内存。这可能会导致在6 GB GPU上为用户调用上述机制，从而降低应用程序速度。在546.01及更高版本的驱动程序中，我们添加了一个禁用共享内存的设置，如果用户使用需要更多GPU内存的设置，这将使性能在崩溃风险下保持稳定。本指南将解释如何执行此操作。
> 因此，解决此问题需要把显卡驱动回退到532及以下；或者更新到546及以上并按[图文教程](https://nvidia.custhelp.com/app/answers/detail/a_id/5490)进行配置
> 注：需要选中的python.exe位置一般在Anaconda(安装路径)/envs/sovits(训练用的虚拟环境名)/python.exe
> 推荐在本地进行驱动更新，也可以在[这里](https://www.nvidia.cn/Download/index.aspx?lang=cn)下载驱动

或者，如果您不想更改共享显存设置，您也可以尝试降低batchsize值以防止共享显存的占用（此处建议8g专用显存设置batchsize=4）

在您进行上述所有更改之后，最好重启一下计算机释放显存后再次开启训练。

**Comment by stephen7943** [comment]
版主您好：

感謝您的回覆，我有嘗試您說的限制使用共享記憶體的與降低batchsize值方式，確實每個epoch耗時下降到80~100，約縮短了10秒，小幅度的加快訓練時間，另外也感謝您替我解惑關於GPU占用的情況！！
