### ISSUE TITLE
如果使用sovits转换声音之后用于训练diffsinger声库，是否可以不用在成品中声明音频来源？

### ISSUE THREAD

**Issue by ILG2021** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#19]
转换的目标声音是我们自己的歌手，没有版权问题。

**Comment by SUC-DriverOld** [comment]
确保数据集来源合法，sovits最新要求就是不要公开说明此项目，仅说明数据来源就行。不过你拿sovits推理出来的音频去做diffsinger，效果可能不会很好

**Comment by ILG2021** [comment]
> 确保数据集来源合法，sovits最新要求就是不要公开说明此项目，仅说明数据来源就行。不过你拿sovits推理出来的音频去做diffsinger，效果可能不会很好

谢谢您的回复，有没有署名的例子啊？

**Comment by SUC-DriverOld** [comment]
暂无，没人专门问这个问题，我个人觉得你直接提一下：声库使用xxx的语音/歌声进行训练，已获授权，就可以了

**Comment by ILG2021** [comment]
你好，想在确认下底模的版权问题，您发布的底模是cc协议对吧？DDSP-SVC的底模您知道是什么协议嘛？

**Comment by SUC-DriverOld** [comment]
是的，我在hf的协议是cc-by-nc-sa4.0协议
ddsp的底模仓库链接是https://huggingface.co/datasets/ms903/Diff-SVC-refactor-pre-trained-model  并没给出协议
你可以尝试在hf给此仓库提discussion

**Comment by ILG2021** [comment]
好的，非常感谢
