### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 23: invalid continuation byte

### ISSUE THREAD

**Issue by Everythingisundercontrol** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#2]
在执行 python train.py -c configs/config.json -m 32k 后报出的，但不知道是哪里有问题，好像看到重复一下生成configs文件的命令后解决的，但我试了一下好像没用

**Comment by SUC-DriverOld** [comment]
**Unicode解码错误：“utf-8”编解码器无法解码位置中的字节0x43:继续字节无效**
请尝试更改编码器的编码类型为```utf-8```（不要使用GBK）重新保存后重试
或者直接在每个代码文件开头添加
```shell
# -*- coding: utf-8 -*-
```
即可解决
