### ISSUE TITLE
能否将文字转音频的功能提供API提供前端使用？

### ISSUE THREAD

**Issue by TzyTman** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#20]

**Comment by SUC-DriverOld** [comment]
sovits的文字转音频**未提供**api接口，其原理是先调用edge-tts生成语音，再进行音频转音频。
你可以根据上述原理手动构建。但

如果要使用api，建议换[GPT-Sovits](https://github.com/RVC-Boss/GPT-SoVITS)项目。此项目的tts具有情感，对训练集的要求更低，训练时长更短，更推荐。（此项目提供了api）

**Comment by Imfdj** [comment]
> sovits的文字转音频**未提供**api接口，其原理是先调用edge-tts生成语音，再进行音频转音频。 你可以根据上述原理手动构建。但
> 
> 如果要使用api，建议换[GPT-Sovits](https://github.com/RVC-Boss/GPT-SoVITS)项目。此项目的tts具有情感，对训练集的要求更低，训练时长更短，更推荐。（此项目提供了api）

[GPT-Sovits](https://github.com/RVC-Boss/GPT-SoVITS) 情感还没实现呢。。。 为什么你会说“此项目的tts具有情感”，是有什么其他的方式吗？
![image](https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/assets/25856248/027100fc-afb6-41ab-9fb7-ea9eb475d876)

**Comment by SUC-DriverOld** [comment]
enhance是增强，目前的情感基于的是参考音频实现的
