### ISSUE TITLE
如果编码器选择whisper-ppg-large，后面训练扩散模型时会有模型参数shape不匹配的错误。

### ISSUE THREAD

**Issue by Oliver0621** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#21]
![image](https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/assets/137243056/1ab04ed1-c3d3-42e2-8cd3-a51e136d2156)
这里给的训练扩散模型的底模是适合vec768l12编码器的，如果前面选择编码器那一步选择whisper-ppg-large，后面在训练扩散模型时，会出现这个错误，导致无法训练。

![image](https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/assets/137243056/78431011-80e9-45d3-8e67-ea318cb3475b)

请问有适合 whisper-ppg-large的扩散模型底模吗？

**Comment by SUC-DriverOld** [comment]
社区暂无公开的whisper-ppg-large的底模，只有whisper-ppg的底模，我已更新到文档中，https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/blob/4.1/README_zh_CN.md#222-%E9%A2%84%E8%AE%AD%E7%BB%83%E5%BA%95%E6%A8%A1-%E5%BC%BA%E7%83%88%E5%BB%BA%E8%AE%AE%E4%BD%BF%E7%94%A8

使用whisper-ppg-large你可能需要无底模训练

**Comment by SUC-DriverOld** [comment]
社区只有whisper-ppg的扩散底模，我已更新到文档中，https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/blob/4.1/README_zh_CN.md#222-%E9%A2%84%E8%AE%AD%E7%BB%83%E5%BA%95%E6%A8%A1-%E5%BC%BA%E7%83%88%E5%BB%BA%E8%AE%AE%E4%BD%BF%E7%94%A8

https://github.com/SUC-DriverOld/so-vits-svc-Deployment-Documents/releases/tag/v24.6.21
