### ISSUE TITLE
请教下那款软件的唱歌变声效果最好

### ISSUE THREAD

**Issue by ILG2021** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#23]
方案如下：
RVC
sovits 4.1：whisper + diffusion
sovits 5.0，现已改名是whisper svc
Amphion MultipleContentSVC
kits ai，商业
audimee，商业

**Comment by SUC-DriverOld** [comment]
各有各的优势，我自己都没有完全使用过
不好做评价，看你自己需求
